# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancel in-progress runs for the same workflow and branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write  # For test result publishing
  pull-requests: write  # For commenting on PRs
  id-token: write # For Codecov

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: 'BY WMS 2020.1.1 QA'
    env:
      CF_PROXY_PORT: 4600

    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - uses: Voodoo262/cloudflare-access-proxy@49fb7aa6d7708630e1a94d2096caa765344617eb # v1.0.1
      with:
        cf-access-client-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        target-url: ${{ secrets.CF_ACCESS_TARGET_URL }}
        listen-port: ${{ env.CF_PROXY_PORT }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        cache-provider: basic

    - name: Build with Gradle
      env:
        MOCA_URL: 'http://localhost:${{ env.CF_PROXY_PORT }}/service'
        MOCA_HOST: ${{ vars.MOCA_HOST }} # Not used yet
        MOCA_PORT: ${{ vars.MOCA_PORT }} # Not used yet
        MOCA_USER: ${{ secrets.MOCA_USER }}
        MOCA_PASS: ${{ secrets.MOCA_PASS }}
      run: ./gradlew build

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: (!cancelled())
      with:
        name: test-results
        path: build/test-results/**/*.xml
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      if: (!cancelled())
      with:
        use_oidc: true
        slug: labelzoom/labelzoom-moca-client-java
        fail_ci_if_error: false
