name: 'Test Report'
on:
  workflow_run:
    workflows: ['Gradle Build']           # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
      with:
        artifact: test-results            # artifact name
        name: JUnit Tests                 # Name of the check run which will be created
        path: '**/*.xml'                  # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
        use-actions-summary: false        # Publish summary to Checks on PR rather than Actions Summary
